story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tdd.urls')),
]

tdd/urls.py
from django.urls import path
from . import views

app_name = 'tdd'

urlpatterns = [
    path('', views.index, name='home'),
]

tdd/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    activity = models.CharField(max_length=100)
    
    def __str__(self):
        return '%s' % self.activity

tdd/forms.py
from django.forms import ModelForm
from .models import Message

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

tdd/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Message
from .forms import MessageForm

# Create your views here.

def index(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            data_item = form.save(commit=False)
            data_item.save()
            return HttpResponseRedirect('/')
    form = MessageForm()
    allmessage = Message.objects.all().order_by('-date')
    return render(request, 'tdd/home.html', {'form':form, 'allmessage':allmessage})

tdd/templates/tdd/base.html
<!doctype html>
{% load static %}
<html lang="en">

    <body class="background">
        <head>
            
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link rel="stylesheet" href="{% static 'tdd/style.css' %}">
            <link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
            <link rel="stylesheet" type="text/css" href="{% static 'tdd/css/bootstrap.min.css' %}">

        </head>

            {% block content %}{% endblock %}

            <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
            <script type="text/javascript" src="{% static 'tdd/js/bootstrap.min.js' %}"></script>
    
    </body>
	
</html>

tdd/templates/tdd/home.html
{% extends "tdd/base.html" %}
{% load static %}

	{% block content %}
	<div class="container">

		<div class="col-sm text-center welcome">
			<h1>Hello, World!</h1>
		</div>

		<div class="col-sm pour">
			Pour your thoughts here!
		</div>

		<div>
			<form method="POST" action="">
				{% csrf_token %}
				<div class="input-group mb-3">
					<input type="text" class="form-control form-color" placeholder="What's on your mind..." aria-label="Recipient's username"
						aria-describedby="button-addon2" name="activity" maxlength="100" required id="id_activity">
					<div class="input-group-append">
						<button class="btn submit-button" type="submit" id="button-addon2">POST!</button>
					</div>
				</div>
			</form> 
		</div>

		<div class="row">
			{% for data in allmessage %}
			<div class="col-sm-6 col-md-auto message-card text-center">
			  	<div class="card">
					<div class="card-body">
						<h5 class="card-title">{{data.activity}}</h5>
						<p class="card-text">{{data.date}}</p>
					</div>
				</div>
			</div>
		{% endfor %}
		</div>

	</div>

{% endblock %}